name: Problem Matchers
on:
  push:
    paths:
      - 'scripts/generate-actionlint-matcher/*.js'
      - 'testdata/examples/*.out'
      - 'testdata/err/*.out'
    branches:
      - main
    tags-ignore:
      - '*'
  workflow_dispatch:

jobs:
  matcher-test:
    name: Test generate-actionlint-matcher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version: '1.23'
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: "lts/*"
      - name: Update test data
        run: make ./scripts/generate-actionlint-matcher/test/* SKIP_GO_GENERATE=true
      - name: Test actionlint-matcher.json
        run: node ./scripts/generate-actionlint-matcher/test.mjs
      - name: Ensure .github/actionlint-matcher.json is up-to-date
        run: |
          make .github/actionlint-matcher.json
          if git diff --quiet; then
            echo 'OK'
          else
            echo 'ERROR! .github/actionlint-matcher.json is outdated. Update it by "make .github/actionlint-matcher.json"' >&2
            set -x
            git diff
            exit 1
          fi
