name: Release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ruby/setup-ruby@1d542747a7bad621e02253945b8491142044d3b7 # v1
        with:
          ruby-version: '3.3'
      - run: gem install ronn
      - run: ronn ./man/actionlint.1.ronn
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version: '1.23'
      - uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Post-release download check
        run: bash ./scripts/download-actionlint.bash "${GITHUB_REF#refs/tags/v}"
      - name: Clone nested repository to make version bump commit
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          path: ./tmp-actionlint-for-update-ver
          ref: main
          fetch-depth: 0
      - name: Update version in download script
        run: |
          set -x
          ver="${GITHUB_REF#refs/tags/v}"
          cd ./tmp-actionlint-for-update-ver
          sed -i -E "s/version=\"[0-9]+\\.[0-9]+\\.[0-9]+\"/version=\"${ver}\"/" ./scripts/download-actionlint.bash
          git diff
          git add ./scripts/download-actionlint.bash
          git -c user.email='41898282+github-actions[bot]@users.noreply.github.com' -c user.name='github-actions[bot]' commit -m "update version to $ver in download-actionlint.bash"
          git log -n 1
          git push
  winget:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: rhysd.actionlint
          installers-regex: '_windows_\w+\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Get tag name
        id: tag
        run: |
          echo "name=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3
      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: rhysd
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            GOLANG_VER=1.23
            ACTIONLINT_VER=${{ steps.tag.outputs.name }}
          push: true
          tags: |
            rhysd/actionlint:${{ steps.tag.outputs.name }}
            rhysd/actionlint:latest
